CaddyDz/Turbo

resources/lang/en/footer.php
resources/lang/fr.json
resources/lang/fr/footer.php
resources/views/layouts/footer.blade.php

Localize footer links closes #126

---

resources/views/about.blade.php
resources/views/index.blade.php
resources/views/layouts/app.blade.php
resources/views/layouts/header.blade.php
resources/views/partials/mobile_menu.blade.php
resources/views/partials/reviews.blade.php
resources/views/partials/team.blade.php

Link to static assets from the base URL

---

resources/lang/fr.json
tests/Feature/ChangePasswordTest.php

Tested password change and confirmation

---

app/Http/Controllers/AccountController.php
app/Http/Requests/ChangePasswordRequest.php
resources/lang/fr.json
resources/views/auth/passwords/change.blade.php
resources/views/dashboard.blade.php
resources/views/partials/account_navigation.blade.php
routes/web.php
tests/Feature/ChangePasswordTest.php

Allow users to change their password

---

.github/labeler.yml
.github/workflows/label.yml

[skip ci] Added labeler workflow config

---

app/Http/Controllers/LocalizationController.php
app/Http/Kernel.php
app/Http/Middleware/Locale.php
resources/lang/fr.json
resources/views/layouts/topbar.blade.php
resources/views/partials/languageSwitcher.blade.php
tests/Feature/LocalizationTest.php

Users can change application language

---

package-lock.json
package.json

Updated node dependencies

---

package.json

Updated laravel mix

---

resources/views/auth/login.blade.php
resources/views/auth/passwords/change.blade.php
resources/views/auth/passwords/confirm.blade.php
resources/views/dashboard.blade.php
resources/views/layouts/block.blade.php
tests/Feature/ChangePasswordTest.php
tests/Feature/PagesTest.php

Moved post header and pre footer to block layout

---

README.md

* These are optional libraries for image optimization
* I excluded ffmpeg because we don't process video
* Installation commands for both Linux and macOS

Added media library prerequisites

---

app/Providers/RouteServiceProvider.php
routes/dev.php
tests/Feature/RoutesTest.php

Added dev route to test mailables

---

.vscode/launch.json
app/Http/Controllers/SearchController.php
tests/Feature/SearchTest.php

Added chrome debugger config

---

resources/views/layouts/header.blade.php
resources/views/layouts/topbar.blade.php
resources/views/partials/mobile_menu.blade.php

Temporarily comment track order markup

---

resources/lang/fr.json
resources/views/contact.blade.php
resources/views/errors/419.blade.php

* Closes #137 
* Also localized strings

Created a 419 page expired error page

---

.gitignore
.travis.yml
app/Console/Kernel.php
app/Nova/Option.php
app/Nova/Resource.php
app/Nova/Templates/HeaderOptions.php
app/Nova/User.php
app/Observers/PartObserver.php
app/Observers/ProfileObserver.php
app/Providers/AppServiceProvider.php
app/Providers/HorizonServiceProvider.php
app/Providers/NovaServiceProvider.php
app/Providers/ObserverServiceProvider.php
config/app.php
config/nova-translatable.php
config/nova.php
config/novapage.php

* Take snapshot for metrics
* Darken the UI

Horizon queues dashboard config

---

.gitignore
database/factories/PartFactory.php
database/migrations/2020_06_11_114134_create_parts_table.php
database/seeds/DatabaseSeeder.php
database/seeds/UserSeeder.php
database/seeds/VehicleSeeder.php

Seed database

---

config/ignition.php

Dark theme for exceptions and open in VSCode

---

app/Exceptions/Handler.php

Convert method not allowed exceptions to 404

---

resources/views/auth/passwords/email.blade.php
resources/views/auth/passwords/reset.blade.php
resources/views/partials/account_menu.blade.php

Reset password views

---

app/CustomPathGenerator.php
config/media-library.php
database/seeds/DatabaseSeeder.php

Customize file paths

---

resources/lang/fr.json
resources/views/errors/403.blade.php
resources/views/partials/account_menu.blade.php
routes/dev.php

*Added `403.blade.php` to `errors/views/resouress`
*closes #194 

Added signature invalid error page

---

composer.lock

Updated composer dependencies

---

app/Http/Controllers/PartsController.php
database/seeds/VehicleSeeder.php
package-lock.json
package.json
resources/js/app.js
resources/js/components/HeaderSearch.vue
resources/lang/fr.json
routes/web.php

Instant search in header

---

.gitignore
resources/views/layouts/header/navbar.blade.php

Fixed sidebar images

---

.gitignore
resources/views/layouts/app.blade.php
resources/views/parts/list_item.blade.php

Link to secure assets

---

resources/views/contact.blade.php

[ci skip] Enabled CSRF and unicode in contact form

---

app/Nova/Templates/FooterOptions.php
resources/lang/fr.json
resources/lang/option/footer.json
resources/views/layouts/footer.blade.php

* Added social links in the footer.
* Added to the admin panel so he can change them 

footer social links

---

resources/views/about.blade.php
resources/views/cart.blade.php
resources/views/index.blade.php
resources/views/partials/reviews.blade.php
resources/views/partials/team.blade.php
resources/views/search/results.blade.php
resources/views/wishlist.blade.php

* * Replaced  `alt=""` with `alt="@lang('Photo')"`
* closes #242 

alt="" shit

---

app/Nova/Part.php

Show parts created by auth user in admin panel

---

app/Http/Controllers/SupplierController.php
app/Nova/Supplier.php
app/Supplier.php
app/User.php
database/factories/SupplierFactory.php
database/migrations/2020_06_22_165956_create_suppliers_table.php
database/seeds/DatabaseSeeder.php
database/seeds/SupplierSeeder.php
database/seeds/UserSeeder.php

Added suppliers model

---

.github/labeler.yml
app/Nova/Part.php
app/Nova/Supplier.php
app/Nova/User.php
composer.json
composer.lock
resources/lang/fr.json

Localize admin panel

---

app/Category.php
app/Order.php
app/Part.php
app/Profile.php
app/Supplier.php
app/Type.php
app/User.php
app/Vehicle.php

Added docs blocks to models

---

app/Nova/Part.php
app/Part.php
database/migrations/2020_06_11_114134_create_parts_table.php

Soft delete part model

---

app/Console/Commands/CreateAdmin.php

* Closes #282
* Necessary to start using site without data
* Use by `php artisan admin:create`

Added a create admin command

---

app/Category.php
app/Nova/Category.php
app/Nova/Type.php
app/Observers/TypeObserver.php
app/Type.php
public/css/header.css
resources/lang/fr.json
resources/views/layouts/header/megamenu.blade.php
resources/views/layouts/header/navbar.blade.php

* Closes #278 
* Some minor UI fixes

Create categories and types from admin panel

---

app/Brand.php
app/Http/Controllers/BrandsController.php
app/Http/Controllers/VehiclesController.php
app/Http/Requests/BrandModelsRequest.php
app/Http/Requests/SearchRequest.php
app/Observers/BrandObserver.php
app/Providers/AppServiceProvider.php
app/Providers/ObserverServiceProvider.php
app/Vehicle.php
database/factories/BrandFactory.php
database/factories/VehicleFactory.php
database/migrations/2020_06_11_061407_create_brands_table.php
database/migrations/2020_06_11_064253_create_vehicles_table.php
database/migrations/2020_06_25_161407_create_brands_table.php
database/seeds/BrandSeeder.php
database/seeds/DatabaseSeeder.php
database/seeds/VehicleSeeder.php
database/seeds/data/brands.php
public/js/finder.js
public/js/main.js
resources/views/brand.blade.php
resources/views/index.blade.php
resources/views/layouts/app.blade.php
resources/views/partials/brands.blade.php
resources/views/partials/finder.blade.php
routes/web.php
tests/Feature/FinderTest.php
tests/Feature/SearchTest.php

Parts by brand

---

database/seeds/data/brands.php

* Added brands to welcome page 

car brands

---

app/Category.php
app/Type.php
database/seeds/PartSeeder.php

Apply CS fixes

---

app/Category.php
app/Http/Controllers/PartsController.php
app/Http/Controllers/TypesController.php
app/Http/Controllers/WorkshopController.php
app/User.php
app/Workshop.php
database/migrations/2020_07_03_154307_create_workshops_table.php
resources/views/layouts/header/navbar.blade.php
resources/views/partials/account_menu.blade.php
resources/views/partials/account_navigation.blade.php
resources/views/partials/mobile_menu_indicators.blade.php
resources/views/partials/mobile_menu_links.blade.php
resources/views/shop.blade.php
routes/web.php

Workshops and shops 

---

app/Nova/Receipt.php
app/Receipt.php
database/migrations/2020_07_04_111657_create_receipts_table.php
resources/lang/fr.json
resources/views/print/receipt.blade.php

VAT on client receipt

---

composer.json
composer.lock

Made admin panel responsive

---

app/Nova/Invoice.php
app/Nova/Receipt.php
app/Nova/Resource.php
composer.json
composer.lock

Search receipt by client and invoice by supplier

---

.gitignore
app/Http/Controllers/PartsController.php
app/Http/Controllers/ReviewsController.php
app/Http/Requests/ReviewPartRequest.php
app/Observers/ReviewObserver.php
app/Part.php
app/Providers/ObserverServiceProvider.php
app/Review.php
database/factories/ReviewFactory.php
database/migrations/2020_07_06_135952_create_reviews_table.php
database/seeds/DatabaseSeeder.php
database/seeds/ReviewSeeder.php
resources/lang/fr.json
resources/views/auth/login.blade.php
resources/views/part.blade.php
resources/views/partials/part/reviews.blade.php
resources/views/vendor/pagination/.gitignore
resources/views/vendor/pagination/bootstrap-4.blade.php
routes/web.php

Allow users to review parts

---

app/Category.php
app/Http/Controllers/PartsController.php
app/Http/Requests/StorePartRequest.php
app/Nova/Part.php
app/Part.php
database/factories/PartFactory.php
database/migrations/2020_06_11_114134_create_parts_table.php
resources/js/app.js
resources/js/components/KeyFeatures.vue
resources/lang/fr.json
resources/views/layouts/app.blade.php
resources/views/part.blade.php
resources/views/shop.blade.php

Added key features to parts

---

app/Observers/PartObserver.php
database/factories/PartFactory.php
database/migrations/2020_06_11_114134_create_parts_table.php
resources/views/part.blade.php

Added excerpt to parts

---

app/Discount.php
app/Http/Controllers/DiscountController.php
app/Nova/Discount.php
app/Policies/DiscountPolicy.php
database/factories/DiscountFactory.php
database/migrations/2020_07_13_085420_create_discounts_table.php
database/seeds/DatabaseSeeder.php
database/seeds/DiscountSeeder.php

Discount base architeture

---

resources/views/print/receipt.blade.php

Show part brand in receipt

---

app/Compatibility.php
app/Http/Controllers/CompatibilityController.php
app/Nova/Category.php
app/Nova/Client.php
app/Nova/Compatibility.php
app/Nova/Discount.php
app/Nova/Invoice.php
app/Nova/Order.php
app/Nova/Part.php
app/Nova/Receipt.php
app/Nova/Supplier.php
app/Nova/User.php
app/Nova/Vehicle.php
app/Part.php
database/migrations/2020_07_13_152433_create_compatibilities_table.php
database/seeds/Compatibility.php
resources/views/print/receipt.blade.php

Show part compatible vehicles in receipt

---

app/Observers/PartObserver.php

Set old price on part update

---

app/Observers/CategoryObserver.php
app/Observers/PartObserver.php

Move attribute assignments to updating event in observers

---

app/Nova/Brand.php
app/Policies/BrandPolicy.php
app/Providers/AuthServiceProvider.php
database/seeds/PartSeeder.php
database/seeds/data/brands.php
resources/lang/fr.json

Prevent deleting brands with vehicles

---

app/Http/Controllers/StockController.php
app/Nova/Stock.php
app/Observers/PartObserver.php
app/Policies/StockPolicy.php
app/Stock.php
app/User.php
config/ide-helper.php
database/factories/StockFactory.php
database/migrations/2020_07_17_080240_create_stocks_table.php
database/seeds/DatabaseSeeder.php
database/seeds/StockSeeder.php

Personal stock

---

app/Http/Controllers/ProfileController.php
app/Http/Requests/UpdateProfileRequest.php
app/Observers/UserObserver.php
app/Providers/ObserverServiceProvider.php
resources/views/partials/account_navigation.blade.php
resources/views/profile.blade.php
routes/web.php

Update profile info

---

resources/views/auth/login.blade.php
resources/views/dashboard.blade.php
routes/web.php

Fixed lost auth user on 404

---

app/Http/Controllers/PartsController.php
app/Nova/Actions/ChangePartViews.php
app/Nova/Part.php
app/Part.php
config/nova.php
database/factories/PartFactory.php
database/seeds/RoleSeeder.php
resources/lang/fr.json

Allow admin to modify part view count

---

app/Invoice.php
app/InvoicePart.php
app/Jobs/UpdateStockFromInvoice.php
app/Jobs/UpdateStockFromReceipt.php
app/Nova/Invoice.php
app/Nova/Receipt.php
app/Nova/Receipt/Part.php
app/Observers/InvoiceObserver.php
app/Observers/ReceiptObserver.php
database/migrations/2020_06_25_095056_create_invoice_part_table.php
resources/lang/fr.json

Update stock from receipt and invoice

---

resources/views/part.blade.php

*  localize `part.blade.php`
*  replacing svgs with @include
* closes #307  

Localize features in the part view

---

public/css/style.css
resources/js/app.js
resources/views/shop.blade.php

* Hided Add part in shop by default to on click 
* closes #355 

Hide add part in shop view by default

---

app/Http/Controllers/StoresController.php
app/Observers/StoreObserver.php
app/Part.php
app/Policies/StoreContactPolicy.php
app/Providers/AppServiceProvider.php
app/Providers/ObserverServiceProvider.php
app/Store.php
app/User.php
database/migrations/2020_07_19_135745_create_stores_table.php
resources/views/part.blade.php
resources/views/store/index.blade.php
routes/web.php

Link to store

---

composer.json
composer.lock
config/nova-theme-responsive.php

Responsive inline relation modal

---

app/Nova/Part.php
app/Part.php
database/migrations/2020_06_22_165956_create_suppliers_table.php
database/migrations/2020_07_22_151701_create_part_vehicle_table.php
nova-components/NovaPreviewResource/dist/js/field.js
nova-components/NovaPreviewResource/resources/js/components/IndexField.vue
nova-components/NovaPreviewResource/src/NovaPreviewResource.php

Preview parts in index

---

public/css/pricing.css
resources/views/pricing.blade.php
routes/web.php

Pricing page

---

app/Http/Controllers/StoreAboutController.php
app/Http/Resources/StoreAbout.php
app/Nova/StoreAbout.php
app/Nova/StoreContact.php
app/Observers/StoreAboutObserver.php
app/Policies/StoreAboutPolicy.php
app/Providers/ObserverServiceProvider.php
app/Store.php
app/StoreAbout.php
database/factories/StoreAboutFactory.php
database/migrations/2020_07_26_144414_create_store_abouts_table.php
database/seeds/StoreAboutSeeder.php
public/css/style.css
resources/views/store/about.blade.php
resources/views/store/index.blade.php
routes/web.php
tests/Feature/StoreTest.php

Store about page

---

app/Nova/Part.php

Remove images from part excel export

---

.styleci.yml
app/Nova/Receipt.php
app/Nova/Receipt/Part.php
database/factories/StockFactory.php

Allow addition of parts to receipts by reference

---

app/Nova/Client.php
app/Nova/Supplier.php
app/Nova/Templates/FooterOptions.php

Use Place field for addresses

---

app/Nova/Bill.php
app/Nova/Receipt.php
database/seeds/ClientSeeder.php
resources/lang/fr.json

Separate (create a new receipt) one with client and one without

---

app/Observers/VehicleModelObserver.php
app/Providers/ObserverServiceProvider.php
app/VehicleModel.php
database/migrations/2020_08_19_145354_create_vehicle_models_table.php
database/seeds/ModelSeeder.php

* Closes #427
Signed-off-by: titania1 <widadwid.ww@gmail.com>

Added slug to vehicle models

---

app/Engine.php
app/Helpers.php
app/Http/Controllers/EngineController.php
app/Http/Controllers/EnginesController.php
app/VehicleModel.php
database/migrations/2020_08_27_153058_create_engines_table.php
database/seeds/EngineSeeder.php
public/js/main.js
resources/lang/fr.json
resources/views/brand.blade.php
resources/views/model.blade.php
routes/web.php

* Seed engines from models
* Link to model engines
* Show engine data
* Closes #426

Engines catalog

---

app/Nova/Part.php
app/Observers/PartObserver.php
app/Part.php

Fix part price update in admin

---

app/Nova/Resource.php

Use scout for nova only if available

---

database/migrations/2020_06_10_125309_create_vehicles_table.php
resources/views/faq.blade.php

Signed-off-by: titania1 <widadwid.ww@gmail.com>

Linked Contact-us button
